/* Diccionario español → inglés de la interfaz  ·  ver ui/idioma.js.
 *
 * Una entrada por texto tal como está escrito en el código (o en el HTML).
 * Las que llevan {0}, {1}… son plantillas: casan con lo que el código compone
 * con números o nombres dentro. Lo que no esté aquí sale en español, sin
 * romper nada: si al usar la app en inglés se cuela una frase en español,
 * es que falta aquí.
 */
const IDIOMA_EN = {
  // --- encabezado, inicio y barra de archivo ------------------------------
  "shape101 — Taller 101": "shape101 — Taller 101",
  "Dibujo 2D para taller · Taller 101": "2D drafting · Taller 101",
  "Volver al dibujo abierto (Esc)": "Back to the open drawing (Esc)",
  "Vaciar la lista": "Clear the list",
  "Pantalla de inicio (Ctrl+I)": "Start screen (Ctrl+I)",
  "Nuevo dibujo": "New drawing",
  "Abrir DXF, DWG o .t101d (Ctrl+O)": "Open DXF, DWG or .t101d (Ctrl+O)",
  "Guardar .t101d (Ctrl+S)": "Save .t101d (Ctrl+S)",
  "Guardar con otro nombre (Ctrl+Shift+S)": "Save under another name (Ctrl+Shift+S)",
  "Exportar DXF R2013": "Export DXF R2013",
  "Deshacer (Ctrl+Z)": "Undo (Ctrl+Z)",
  "Rehacer (Ctrl+Y)": "Redo (Ctrl+Y)",
  "Encuadrar todo (doble clic en el lienzo)": "Zoom extents (double-click the canvas)",
  "Medir distancia entre dos puntos (MD)": "Measure the distance between two points (MD)",
  "Claro / oscuro": "Light / dark",
  "Hay cambios sin guardar": "There are unsaved changes",
  "Dibujo nuevo (Ctrl+N)": "New drawing (Ctrl+N)",
  "Nuevo": "New", "Abrir…": "Open…", "Guardar": "Save", "Guardar como…": "Save as…",
  "Exportar DXF…": "Export DXF…", "Encuadrar": "Extents", "Medir": "Measure",
  "Sin título": "Untitled",
  "Dibujo nuevo": "New drawing",
  "Hoja en blanco, capas 0 y COTAS": "Blank sheet, layers 0 and COTAS",
  "Abrir un plano…": "Open a drawing…",
  "DWG, DXF o .t101d": "DWG, DXF or .t101d",
  "Traer de Taller 101…": "Import from Taller 101…",
  "Un mueble .t101x ya despiezado": "A .t101x cabinet, already cut-listed",
  "Recientes": "Recent", "limpiar": "clear",
  "Todo va en milímetros. El modelo se dibuja a 1:1.": "Everything is in millimetres. The model is drawn at 1:1.",
  "Dibujo nuevo.": "New drawing.",
  "Todavía no has abierto ningún plano.": "You haven't opened any drawing yet.",
  "versión {0}": "version {0}",
  "Ayuda": "Help", "Ayuda ▾": "Help ▾",
  "Comandos (AYUDA)": "Commands (HELP)",
  "Configuración de shape101…": "shape101 settings…",
  "Instalar ODA File Converter…": "Install ODA File Converter…",
  "Acerca de shape101": "About shape101",
  "Licencias de terceros…": "Third-party licenses…",
  "Unidades del dibujo": "Drawing units", "Unidades del dibujo…": "Drawing units…",
  "Guía de herramientas (PDF)…": "Tool guide (PDF)…", "Guía de herramientas abierta.": "Tool guide opened.",
  "Abre la guía de herramientas en PDF: icono, nombre y qué hace cada una": "Opens the tool guide PDF: icon, name and what each tool does",
  "Cambiarla escala lo dibujado para conservar su tamaño real (UNIDADES).": "Changing it scales what is drawn to keep its real size (UNITS).",
  "Centrar el dibujo": "Center the drawing", "El dibujo quedó centrado en la ventana.": "The drawing is now centered in the viewport.",
  "La escala se escribe como 1:50.": "Write the scale as 1:50.",
  "Escala de la hoja: 1:{0}. La ventana se dibujó a esa escala.": "Sheet scale: 1:{0}. The viewport was drawn at that scale.",
  "Clic en la hoja: ese punto queda al centro (Enter o T: todo el dibujo)": "Click on the sheet: that point goes to the center (Enter or T: the whole drawing)",
  "Ventana centrada en {0}, {1} {2}.": "Viewport centered at {0}, {1} {2}.", "Esta hoja no tiene ventana.": "This sheet has no viewport.",
  "Centra el dibujo en la ventana de la hoja (Enter: todo el dibujo; clic: ese punto al centro)": "Centers the drawing in the sheet viewport (Enter: whole drawing; click: that point to the center)", "Unidad de trabajo": "Working unit", "milímetros": "millimeters", "centímetros": "centimeters", "metros": "meters",
  "Escalar lo dibujado para conservar el tamaño real": "Scale what is drawn to keep its real size",
  "Todo lo que se teclea, se ve y se acota va en esta unidad; el DXF sale con ella declarada. Con «escalar», la mesa de 600 mm pasa a medir 0.6 m; sin escalar, los números se quedan y sólo cambia lo que significan.": "Everything you type, see and dimension is in this unit; the DXF declares it. With “scale”, a 600 mm table becomes 0.6 m; without it, the numbers stay and only their meaning changes.",
  "Unidades: {0}.": "Units: {0}.", "El dibujo ya está en {0}.": "The drawing is already in {0}.",
  "Unidades: {0} (lo dibujado se escaló ×{1}; las cotas con {2} decimales).": "Units: {0} (drawing scaled ×{1}; dimensions with {2} decimals).",
  "Unidades: {0} (sin escalar: los números se quedan).": "Units: {0} (not scaled: numbers stay).",
  "Cambia la unidad de trabajo del dibujo: mm, cm o m": "Change the drawing's working unit: mm, cm or m",
  // Pregunta con valor por omisión: «Distancia del desfase <60>» → traduce la pregunta y conserva el valor.
  "{0} <{1}>": "{0} <{1}>",
  "Buscar actualizaciones…": "Check for updates…",
  "Avisos de Taller 101…": "Taller 101 notices…",
  "Avisos de Taller 101": "Taller 101 notices",
  "Actualizaciones de shape101": "shape101 updates",
  "Instalar shape101 {0}": "Install shape101 {0}",
  "El instalador ya está bajado y comprobado. Para instalarlo shape101 se cierra; guarda tus cambios antes. El instalador quita la versión anterior solo.": "The installer is downloaded and verified. shape101 will close to install it; save your changes first. The installer removes the previous version by itself.",
  "Instalar ahora": "Install now", "Después": "Later",
  "Hay cambios sin guardar": "There are unsaved changes",
  "Guarda primero (GUARDAR) y vuelve a pedir la instalación con ACTUALIZAR, o instala de todos modos y pierde los cambios.": "Save first (SAVE) and ask again with UPDATE, or install anyway and lose the changes.",
  "Instalar y perder los cambios": "Install and lose changes", "Guardar primero": "Save first",
  "El instalador quedó en {0}. Ábrelo a mano.": "The installer is at {0}. Open it by hand.",
  "Instalando shape101 {0}. La aplicación se cierra…": "Installing shape101 {0}. The application is closing…",
  "Bajando shape101 {0}…": "Downloading shape101 {0}…",
  "Hay una versión nueva de shape101: {0} (tienes la {1}). Teclea ACTUALIZAR.": "A new shape101 version is available: {0} (you have {1}). Type UPDATE.",
  "Tienes shape101 {0}.": "You have shape101 {0}.",
  "No se pudo consultar el sitio de Taller 101 (¿sin internet?).": "Could not reach the Taller 101 site (no internet?).",
  "Es la última versión.": "It is the latest version.",
  "Hay una versión nueva: {0} ({1}).": "A new version is available: {0} ({1}).",
  "Descarga de {0} MB; se comprueba con su huella antes de instalar.": "{0} MB download; verified against its checksum before installing.",
  "Desde aquí no se instala en este sistema; se abre la página de descarga.": "Cannot install from here on this system; the download page opens instead.",
  "No volver a avisar de la {0}": "Don't remind me about {0} again",
  "Buscar actualizaciones al arrancar": "Check for updates at startup",
  "Bajar {0}": "Download {0}", "Abrir la descarga": "Open the download", "Ahora no": "Not now",
  "{0} aviso(s) nuevo(s) de Taller 101": "{0} new notice(s) from Taller 101",
  "No hay avisos.": "No notices.", "Leer más": "Read more",
  "{0} aviso(s) nuevo(s) de Taller 101. Teclea AVISOS o abre Ayuda ▾.": "{0} new notice(s) from Taller 101. Type NOTICES or open Help ▾.",
  "Licencias de terceros": "Third-party licenses",
  "shape101 lleva dentro estos componentes de otros. Cada uno viaja con su aviso de licencia, como pide cada licencia.": "shape101 ships these third-party components. Each one travels with its license notice, as each license requires.",
  "Elige un componente para ver el texto de su licencia.": "Pick a component to read its license text.",
  "No se encontró el texto.": "Text not found.",
  "Ayuda y configuración": "Help and settings",

  // --- barra de herramientas ----------------------------------------------
  "Arrastra para moverla · doble clic para anclarla otra vez": "Drag to move it · double-click to dock it again",
  "Trazo": "Draw", "Anotaciones": "Annotate", "Modificar": "Modify", "Bloques": "Blocks", "Hoja": "Sheet",
  "Línea (L)": "Line (L)", "Polilínea (PL)": "Polyline (PL)", "Rectángulo (REC)": "Rectangle (REC)",
  "Círculo (C)": "Circle (C)", "Arco por tres puntos (A)": "Arc through three points (A)",
  "Elipse (EL)": "Ellipse (EL)", "Spline (SPL)": "Spline (SPL)", "Punto (PU)": "Point (PU)", "Rayado (H)": "Hatch (H)",
  "Cota recta (CO_)": "Linear dimension (CO_)", "Cota alineada (CAL)": "Aligned dimension (CAL)",
  "Cotas encadenadas (CC)": "Continued dimensions (CC)", "Cota angular (CAN)": "Angular dimension (CAN)",
  "Radio (CR)": "Radius (CR)", "Diámetro (CD)": "Diameter (CD)", "Directriz con nota (DIR)": "Leader with note (DIR)",
  "Texto (T)": "Text (T)", "Mover (M)": "Move (M)", "Copiar (CP)": "Copy (CP)", "Rotar (RO)": "Rotate (RO)",
  "Escalar (ES)": "Scale (ES)", "Espejo (SI)": "Mirror (SI)", "Desfase (DF)": "Offset (DF)",
  "Recortar (RC)": "Trim (RC)", "Extender (EXT)": "Extend (EXT)", "Empalme (EM)": "Fillet (EM)",
  "Chaflán (CH)": "Chamfer (CH)", "Arreglo (AR)": "Array (AR)", "Estirar (ET)": "Stretch (ET)",
  "Unir en una polilínea (J)": "Join into one polyline (J)", "Explotar en sus partes (X)": "Explode into its parts (X)",
  "Agrupar (Ctrl+G) · DESAGRUPAR con Ctrl+Shift+G · Alt+clic pica uno solo": "Group (Ctrl+G) · UNGROUP with Ctrl+Shift+G · Alt+click picks a single one",
  "Igualar propiedades (IG)": "Match properties (IG)", "Borrar (Supr)": "Erase (Del)",
  "Crear bloque (BL)": "Create block (BL)", "Insertar bloque (IN)": "Insert block (IN)",
  "PDF de fondo para calcar (FONDO)": "Background PDF to trace over (FONDO)",
  "Hoja nueva o editar la hoja (PLANO)": "New sheet, or edit the sheet (PLANO)",
  "Exportar a PDF (PDF)": "Export to PDF (PDF)", "Imprimir en impresora (Ctrl+P)": "Print to a printer (Ctrl+P)",
  "Vista previa de impresión": "Print preview",
  "Arrastra para cambiar el ancho · doble clic para volver al normal": "Drag to change the width · double-click to reset",
  "Ver más líneas de la consola (F2)": "Show more console lines (F2)", "Más líneas": "More lines",
  "Rejilla (F7)": "Grid (F7)", "Forzar el cursor a la rejilla (F9)": "Snap the cursor to the grid (F9)",
  "Horizontal o vertical (F8)": "Horizontal or vertical (F8)", "Referencias a objetos (F3)": "Object snaps (F3)",
  "Entrada dinámica": "Dynamic input",
  "Versión instalada · escribe VERSION para ver qué trae": "Installed version · type VERSION to see what's in it",
  "Comando:": "Command:", "Entidades": "Entities", "Capas": "Layers", "Activa": "Current",
  "REJILLA": "GRID", "REF": "OSNAP", "Zoom": "Zoom",
  "Long": "Len", "Áng": "Ang",
  "Tab fija · Espacio o Enter aceptan · Esc cancela": "Tab locks · Space or Enter accept · Esc cancels",
  "Trabajando…": "Working…",
  "Modelo": "Model", "Hoja nueva (PLANO)": "New sheet (PLANO)",
  "{0} · {1} ventana(s)": "{0} · {1} viewport(s)",

  // --- capas y propiedades ------------------------------------------------
  "Nueva capa": "New layer", "Borrar": "Erase", "Nombre": "Name", "Color": "Color", "Grosor": "Lineweight",
  "Escala del tipo": "Linetype scale",
  "La escala del tipo de línea tiene que ser mayor que cero.": "Linetype scale must be greater than zero.",
  "Tipo de línea": "Linetype", "Imprime": "Plots", "sí": "yes", "no": "no", "Objeto": "Object",
  "Capa": "Layer", "Capa de trabajo: {0}": "Current layer: {0}", "(varias)": "(various)", "Por capa": "By layer",
  "Por bloque": "By block", "La geometría se edita de una en una.": "Geometry is edited one entity at a time.",
  "Escribe las coordenadas como 100,50": "Type coordinates like 100,50", "Eso no es un número.": "That is not a number.",
  "Del archivo": "From the file", "Entidad": "Entity", "Línea": "Line", "Polilínea": "Polyline", "Círculo": "Circle",
  "Arco": "Arc", "Elipse": "Ellipse", "Spline": "Spline", "Punto": "Point", "Rayado": "Hatch", "Texto": "Text",
  "Texto de párrafo": "Paragraph text", "Cota": "Dimension", "Bloque": "Block", "Imagen": "Image", "Sólido": "Solid",
  "Grupo": "Group", "Inserción": "Block reference", "Directriz": "Leader",
  "Esa entidad no sirve para esto.": "That entity can't be used for this.",
  "Selecciona las entidades": "Select the entities", "Elige una entidad": "Pick an entity",
  "{0} elementos aquí": "{0} items here", "{0} entidad(es) por {1}.": "{0} entity(ies) by {1}.",
  "cruce": "crossing", "ventana": "window",
  "Selecciona las entidades (Enter termina)": "Select the entities (Enter finishes)",
  "Bloqueada": "Locked", "Visible": "Visible", "Congelada": "Frozen",

  // --- referencias, estilos, ajustes ------------------------------------
  "Referencias encendidas (F3)": "Object snaps on (F3)", "A qué se engancha": "What it snaps to",
  "Puntería": "Aim", "Apertura": "Aperture", "píxeles": "pixels",
  "Cuánto se aleja el cursor y sigue enganchando.": "How far the cursor can be and still snap.",
  "Referencias a objetos": "Object snaps",
  "Se aplican también al jalar un grip: así un extremo se pega a otro.": "They also apply while dragging a grip: that's how one endpoint sticks to another.",
  "Referencias: {0}.": "Object snaps: {0}.", "apagadas": "off", "{0} modo(s)": "{0} mode(s)",
  "Estilo de cota": "Dimension style",
  "Cambiar esto cambia las cotas del plano entero, no sólo las nuevas.": "Changing this changes every dimension in the drawing, not only new ones.",
  "Escala de la cota": "Dimension scale",
  "El DIMSCALE. Al poner el dibujo en una hoja se ajusta solo a la escala de la ventana.": "The DIMSCALE. When the drawing goes on a sheet it adjusts itself to the viewport scale.",
  "Altura": "Height", "mm en papel": "mm on paper", "Decimales": "Decimals", "Sufijo": "Suffix", "mm, cm…": "mm, cm…",
  "Flechas y líneas": "Arrows and lines", "Punta": "Arrowhead", "Tamaño": "Size", "Sobresale": "Extension",
  "Cuánto pasa la línea de extensión de la línea de cota.": "How far the extension line runs past the dimension line.",
  "Hueco": "Gap", "Separación entre la pieza y donde arranca la línea.": "Gap between the object and where the extension line starts.",
  "Aplicar": "Apply", "Aceptar": "OK", "Cancelar": "Cancel", "Cerrar": "Close",
  "Estilo de cota: texto de {0} mm en el dibujo.": "Dimension style: {0} mm text in the drawing.",
  "ODA File Converter instalado. Los DWG se convierten con él desde ahora.": "ODA File Converter installed. DWG files are converted with it from now on.",
  "No se pudo consultar el ODA:": "Couldn't look up the ODA:", "ODA File Converter": "ODA File Converter",
  "Bajando el ODA File Converter…": "Downloading the ODA File Converter…",
  "Instalar o actualizar el ODA File Converter (convierte DWG más rápido y más fiel)": "Install or update the ODA File Converter (converts DWG faster and more faithfully)",
  "Cuadro con los modos de referencia a objetos": "Dialog with the object snap modes",
  "Altura del texto y tamaño de las flechas de las cotas": "Text height and arrow size of the dimensions",
  "Palomita de arquitectura": "Architectural tick", "Flecha llena": "Closed filled", "Flecha abierta": "Open arrow",
  "Instalar": "Install", "Actualizar a {0}": "Update to {0}", "Abrir la página de ODA": "Open the ODA page",
  "Configuración": "Settings", "Configuración de shape101": "shape101 settings",
  "Idioma": "Language", "Inglés": "English", "Español": "Spanish",
  "Tema": "Theme", "Claro": "Light", "Oscuro": "Dark",
  "Los comandos se aceptan en los dos idiomas siempre (LINE y LINEA). Cambiar el idioma recarga la ventana.": "Commands are always accepted in both languages (LINE and LINEA). Changing the language reloads the window.",
  "Idioma: {0}. Recargando…": "Language: {0}. Reloading…",
  "Cambia el idioma de la interfaz y el tema": "Changes the interface language and the theme",
  "Cambia el idioma de la interfaz: IDIOMA EN · IDIOMA ES": "Changes the interface language: IDIOMA EN · IDIOMA ES",

  // --- consola y comandos generales --------------------------------------
  "Abierto: {0} entidades editables": "Opened: {0} editable entities",
  "{0} exportado: {1} entidades": "{0} exported: {1} entities",
  "Deshecho:": "Undone:", "Rehecho:": "Redone:",
  "Trabajo recuperado. Guárdalo con Ctrl+S para conservarlo.": "Work recovered. Save it with Ctrl+S to keep it.",
  "shape101 {0} · {1}\nEscribe VERSION para ver qué trae.": "shape101 {0} · {1}\nType VERSION to see what's in it.",
  "shape101 listo. Teclea AYUDA para la lista de comandos.": "shape101 ready. Type HELP for the list of commands.",
  "100,50 · @100,50 · @100<45 · o clic en el dibujo": "100,50 · @100,50 · @100<45 · or click in the drawing",
  "Comando desconocido: {0}. Teclea AYUDA para la lista.": "Unknown command: {0}. Type HELP for the list.",
  "Cancelado.": "Cancelled.",
  "No entendí «{0}». Usa 100,50 · @100,50 · 100<45 · @100<45": "Didn't understand “{0}”. Use 100,50 · @100,50 · 100<45 · @100<45",
  "Indica un punto": "Specify a point",
  "{0} · {1} {2} fijos — apunta y haz clic": "{0} · {1} {2} locked — aim and click",
  "Valor": "Value", "«{0}» no es un número válido.": "“{0}” is not a valid number.",
  "ZOOM [E extensión · V ventana · P previo · factor]": "ZOOM [E extents · V window · P previous · factor]",
  "Primera esquina de la ventana": "First corner of the window",
  "ZOOM: usa E (extensión), V (ventana), P (previo) o un factor.": "ZOOM: use E (extents), V (window), P (previous) or a factor.",
  "No hay vista anterior.": "There is no previous view.",
  "Encuadra todo el dibujo": "Zooms to the whole drawing",
  "Mueve la vista (o arrastra con el botón central o derecho)": "Pans the view (or drag with the middle or right button)",
  "Arrastra con el botón central, el derecho, o Shift+izquierdo.": "Drag with the middle button, the right one, or Shift+left.",
  "Redibuja el plano fino y rehace el índice (como REGEN de AutoCAD)": "Redraws the drawing at full quality and rebuilds the index (like AutoCAD's REGEN)",
  "Regenerado en {0} ms.": "Regenerated in {0} ms.",
  "Vuelve a pedir el dibujo entero al motor y lo redibuja": "Asks the engine for the whole drawing again and redraws it",
  "Regenerado desde el motor.": "Regenerated from the engine.",
  "Mide cuánto cuesta pintar y navegar en esta máquina, para diagnosticar": "Measures how much painting and navigating cost on this machine, for diagnosis",
  "(copiado al portapapeles: pégalo en el reporte)": "(copied to the clipboard: paste it in the report)",
  "REJILLA [ON · OFF · paso en mm]": "GRID [ON · OFF · step in mm]", "Rejilla de {0} mm.": "Grid of {0} mm.",
  "BORRADOR [ON · OFF] — modo borrador: líneas de 1 px, sin patrones, textos como cajas (más ligero)": "DRAFT [ON · OFF] — draft mode: 1 px lines, no linetypes, texts as boxes (lighter)",
  "SNAP [ON · OFF · paso en mm] — forzar el cursor a la rejilla": "SNAP [ON · OFF · step in mm] — snap the cursor to the grid",
  "Snap de {0} mm.": "Snap of {0} mm.",
  "ORTHO [ON · OFF] — obliga a horizontal o vertical": "ORTHO [ON · OFF] — forces horizontal or vertical",
  "REF [ON · OFF · modo] — referencias a objetos": "OSNAP [ON · OFF · mode] — object snaps",
  "Modos:": "Modes:", "DIN [ON · OFF] — entrada dinámica junto al cursor": "DYN [ON · OFF] — dynamic input next to the cursor",
  "Cambia entre claro y oscuro": "Switches between light and dark",
  "Mide la distancia entre dos puntos": "Measures the distance between two points",
  "Primer punto": "First point", "Segundo punto": "Second point",
  "Distancia {0} {4} · ΔX {1} · ΔY {2} · ángulo {3}°": "Distance {0} {4} · ΔX {1} · ΔY {2} · angle {3}°",
  "Lista los comandos": "Lists the commands",
  "Qué versión es ésta y qué trajo": "Which version this is and what it brought",
  "shape101 {0} · {1} · Taller 101": "shape101 {0} · {1} · Taller 101",
  "— antes, {0} ({1}):": "— before, {0} ({1}):",
  "encendido": "on", "apagado": "off", "encendida": "on", "apagada": "off",
    "Extremo": "Endpoint", "Medio": "Midpoint", "Centro": "Center", "Cuadrante": "Quadrant",
  "Intersección": "Intersection", "Perpendicular": "Perpendicular", "Cercano": "Nearest", "Nodo": "Node",
  "BARRA [izquierda · derecha · arriba · abajo · flotante]": "TOOLBAR [left · right · top · bottom · floating]",
  "¿Dónde va la barra?": "Where does the toolbar go?", "No sé dónde es «{0}».": "Don't know where “{0}” is.",
  "Barra de herramientas: {0}.": "Toolbar: {0}.",
  "izquierda": "left", "derecha": "right", "arriba": "top", "abajo": "bottom", "flotante": "floating",
  "ATAJO <letra> <comando> — inventa tu propio alias": "ATAJO <letter> <command> — make your own alias",
  "No tienes atajos propios. Ej: ATAJO Q CIRCULO": "You have no custom aliases. E.g. ATAJO Q CIRCLE",
  "Atajo {0} quitado.": "Alias {0} removed.", "No existe el comando {0}.": "The command {0} doesn't exist.",
  "{0} → {1}. Se queda guardado.": "{0} → {1}. It's saved.",

  // --- dibujar --------------------------------------------------------------
  "LINEA [M] — líneas encadenadas (Escape termina); con M, una línea dada por su punto medio": "LINE [M] — chained lines (Escape finishes); with M, a line given by its midpoint",
  "Punto medio de la línea": "Midpoint of the line",
  "Un extremo (o teclea el medio largo)": "One endpoint (or type half the length)",
  "Largo cero.": "Zero length.", "Línea de {0} {1}.": "Line of {0} {1}.",
  "Desde el punto": "From point", "Al punto": "To point", "{0} línea(s).": "{0} line(s).",
  "Polilínea. Escribe C para cerrarla; Escape o Enter la termina.": "Polyline. Type C to close it; Escape or Enter finishes it.",
  "Punto inicial": "Start point", "Siguiente punto (C cierra)": "Next point (C closes)",
  "Una polilínea necesita dos puntos.": "A polyline needs two points.",
  "Polilínea de {0} vértices{1}.": "Polyline with {0} vertices{1}.", ", cerrada": ", closed",
  "RECTANGULO [C · 3P · M] — dos esquinas; por el centro; tres puntos (girado); por medidas": "RECTANGLE [C · 3P · M] — two corners; from the center; three points (rotated); by size",
  "Centro del rectángulo": "Center of the rectangle", "Una esquina": "A corner",
  "Un rectángulo de lado cero no se dibuja.": "A rectangle with a zero side can't be drawn.",
  "Rectángulo de {0} × {1} {2}.": "Rectangle of {0} × {1} {2}.",
  "Primera esquina": "First corner", "Segunda esquina (el lado)": "Second corner (the side)", "Lado cero.": "Zero side.",
  "Altura (o teclea la medida)": "Height (or type the size)", "Altura cero.": "Zero height.",
  "Ancho": "Width", "Alto": "Height",
  "Esquina opuesta, o M para dar las medidas": "Opposite corner, or M to type the size",
  "POLIGONO [lados] — polígono regular por centro y vértice (L: por el medio de un lado)": "POLYGON [sides] — regular polygon by center and vertex (L: by the midpoint of a side)",
  "Número de lados": "Number of sides", "Centro del polígono": "Center of the polygon",
  "Un vértice (o L para dar el punto medio de un lado)": "A vertex (or L to give the midpoint of a side)",
  "Punto medio de un lado": "Midpoint of a side", "Radio cero.": "Zero radius.",
  "Polígono de {0} lados, {1} {2} por lado.": "Polygon with {0} sides, {1} {2} per side.",
  "CIRCULO [2P · 3P · D] — centro y radio; dos puntos del diámetro; tres puntos; centro y diámetro": "CIRCLE [2P · 3P · D] — center and radius; two diameter points; three points; center and diameter",
  "Primer punto del círculo": "First point of the circle", "Tercer punto": "Third point",
  "Los tres puntos están en línea recta: no hay círculo.": "The three points are collinear: no circle.",
  "Círculo de ⌀{0} {1}.": "Circle of ⌀{0} {1}.", "Centro del círculo": "Center of the circle",
  "Diámetro (o teclea la medida)": "Diameter (or type the size)", "Diámetro cero.": "Zero diameter.",
  "Primer punto del diámetro": "First point of the diameter", "Segundo punto del diámetro": "Second point of the diameter",
  "Radio (o teclea la medida)": "Radius (or type the size)",
  "Centro del arco": "Center of the arc", "Inicio del arco": "Start of the arc",
  "Final del arco (antihorario)": "End of the arc (counter-clockwise)", "Arco de radio {0} {1}.": "Arc of radius {0} {1}.",
  "Final del arco": "End of the arc", "Los dos extremos son el mismo punto.": "Both ends are the same point.",
  "Radio (o teclea la medida); el arco panza hacia el cursor": "Radius (or type the size); the arc bulges toward the cursor",
  "Ángulo del arco en grados (antihorario; negativo, horario)": "Arc angle in degrees (counter-clockwise; negative, clockwise)",
  "Ángulo cero.": "Zero angle.", "Arco de radio {0} {2} y {1}°.": "Arc of radius {0} {2} and {1}°.",
  "ARCO [CIF · IFR · ICA] — tres puntos; centro-inicio-fin; inicio-fin-radio; inicio-centro-ángulo": "ARC [CIF · IFR · ICA] — three points; center-start-end; start-end-radius; start-center-angle",
  "Punto por el que pasa": "Point it passes through",
  "Los tres puntos están en línea recta: no hay arco.": "The three points are collinear: no arc.",
  "ELIPSE [E] — por centro, extremo del eje y semieje menor; con E, por los dos extremos del eje": "ELLIPSE [E] — by center, axis endpoint and minor semi-axis; with E, by both axis endpoints",
  "Un extremo del eje": "One end of the axis", "El otro extremo del eje": "The other end of the axis",
  "Centro de la elipse": "Center of the ellipse", "Extremo del eje mayor": "End of the major axis",
  "Eje de largo cero.": "Zero-length axis.", "Semieje menor": "Minor semi-axis", "Semieje menor cero.": "Zero minor semi-axis.",
  "Elipse de {0} × {1} {2}.": "Ellipse of {0} × {1} {2}.",
  "SPLINE [CV] — curva que pasa por los puntos que le des; con CV, curva jalada por puntos de control (Bézier). Escape termina.": "SPLINE [CV] — curve through the points you give; with CV, a curve pulled by control points (Bézier). Escape finishes.",
  "Una spline necesita al menos tres puntos.": "A spline needs at least three points.",
  "Spline con {0} puntos de control.": "Spline with {0} control points.", "Spline por {0} puntos.": "Spline through {0} points.",
  "Marca un punto (sirve de nodo para las referencias)": "Marks a point (works as a node for snaps)",
  "Ubicación del punto": "Location of the point",
  "RAYADO [patrón] — raya una polilínea cerrada o un círculo": "HATCH [pattern] — hatches a closed polyline or a circle",
  "Elige el contorno cerrado a rayar": "Pick the closed outline to hatch", "Rayado {0}.": "Hatch {0}.",
  "Texto de una línea": "Single-line text", "Punto de inserción del texto": "Insertion point of the text",
  "MESA DE TRABAJO": "WORKTABLE", "Altura de letra": "Letter height", "Texto «{0}».": "Text “{0}”.",
  "Texto de párrafo, con ancho de columna": "Paragraph text, with column width",
  "Primera esquina del párrafo": "First corner of the paragraph", "Esquina opuesta": "Opposite corner",
  "Enter dentro del recuadro hace renglón nuevo.": "Enter inside the box makes a new line.", "Párrafo creado.": "Paragraph created.",
  "Texto cambiado a «{0}».": "Text changed to “{0}”.",

  // --- cotas ------------------------------------------------------------------
  "Primer punto de la medida": "First point of the measurement", "Segundo punto de la medida": "Second point of the measurement",
  "¿Dónde va la línea de cota?": "Where does the dimension line go?", "Cota puesta.": "Dimension placed.",
  "Cota lineal (horizontal o vertical según los puntos)": "Linear dimension (horizontal or vertical depending on the points)",
  "Cota horizontal forzada": "Forced horizontal dimension", "Cota vertical forzada": "Forced vertical dimension",
  "Cota paralela al segmento medido": "Dimension parallel to the measured segment",
  "Origen de la cadena": "Origin of the chain", "Siguiente punto ({0})": "Next point ({0})",
  "línea base": "baseline", "continua": "continued", "Cadena de {0} cota(s).": "Chain of {0} dimension(s).",
  "Cotas encadenadas una tras otra": "Dimensions chained one after another", "Cotas desde un mismo origen": "Dimensions from the same origin",
  "Mide el ángulo entre dos direcciones": "Measures the angle between two directions",
  "Vértice del ángulo": "Vertex of the angle", "Punto del primer lado": "Point on the first side", "Punto del segundo lado": "Point on the second side",
  "¿Por dónde pasa el arco?": "Where does the arc go?", "Elige el círculo o arco a acotar": "Pick the circle or arc to dimension",
  "¿Hacia dónde sale la cota?": "Which way does the dimension go?",
  "Acota el radio de un círculo o arco": "Dimensions the radius of a circle or arc", "Acota el diámetro de un círculo": "Dimensions the diameter of a circle",
  "Flecha con una nota al final": "Arrow with a note at the end", "¿A qué apunta?": "What does it point at?",
  "Codo de la flecha": "Elbow of the arrow", "Final de la directriz": "End of the leader", "Nota": "Note",
  "Sin nota: no se creó la directriz.": "No note: the leader wasn't created.",

  // --- modificar ----------------------------------------------------------------
  "{0} entidad(es) del archivo original no se movieron:": "{0} entity(ies) from the original file were not moved:",
  "Borra lo seleccionado (tecla Supr)": "Erases the selection (Del key)", "Selecciona lo que se borra": "Select what to erase",
  "{0} entidad(es) borradas.": "{0} entity(ies) erased.", "Selecciona lo que se {0}": "Select what to {0}",
  "copia": "copy", "mueve": "move",
  "Punto base": "Base point", "Destino (Escape termina)": "Destination (Escape finishes)", "{0} copia(s).": "{0} copy(ies).",
  "Destino": "Destination", "Movidas {0}: ΔX {1}, ΔY {2}.": "Moved {0}: ΔX {1}, ΔY {2}.",
  "Mueve lo seleccionado": "Moves the selection", "Copia lo seleccionado": "Copies the selection",
  "Rota lo seleccionado alrededor de un punto": "Rotates the selection around a point", "Selecciona lo que se rota": "Select what to rotate",
  "Centro de giro": "Center of rotation", "Ángulo (o teclea los grados)": "Angle (or type the degrees)",
  "Rotadas {0} entidad(es) {1}°.": "Rotated {0} entity(ies) {1}°.",
  "Escala lo seleccionado desde un punto base": "Scales the selection from a base point", "Selecciona lo que se escala": "Select what to scale",
  "Factor de escala": "Scale factor", "Factor 1: nada que hacer.": "Factor 1: nothing to do.", "Escaladas {0} entidad(es) ×{1}.": "Scaled {0} entity(ies) ×{1}.",
  "Refleja lo seleccionado sobre un eje": "Mirrors the selection across an axis", "Selecciona lo que se refleja": "Select what to mirror",
  "Primer punto del eje": "First point of the axis", "Segundo punto del eje": "Second point of the axis",
  "¿Borrar el original? S/N": "Erase the original? Y/N", "{0} entidad(es) reflejadas.": "{0} entity(ies) mirrored.",
  "{0} copia(s) reflejadas.": "{0} mirrored copy(ies).",
  "Copia una línea, polilínea, círculo o arco a una distancia dada": "Copies a line, polyline, circle or arc at a given distance",
  "Distancia del desfase": "Offset distance", "Elige la entidad a desfasar": "Pick the entity to offset", "¿De qué lado?": "Which side?",
  "El desfase dejaría la figura sin tamaño.": "The offset would leave the shape with no size.",
  "No hay cruce hacia ese lado.": "No intersection on that side.", "El trozo que señalaste no está entre dos cruces.": "The piece you picked isn't between two intersections.",
  "No hay cruce dentro del arco.": "No intersection within the arc.", "Nada que recortar ahí.": "Nothing to trim there.",
  "Quita el trozo de línea o arco que señales": "Removes the piece of line or arc you pick",
  "Alarga una línea hasta lo primero que encuentre": "Extends a line to the first thing it meets",
  "Son la misma línea.": "They are the same line.", "Las dos líneas son paralelas.": "The two lines are parallel.",
  "Redondea la esquina entre dos líneas con un radio": "Rounds the corner between two lines with a radius",
  "Radio del empalme": "Fillet radius", "Esquina a escuadra.": "Square corner.",
  "Las líneas están alineadas: no hay esquina que redondear.": "The lines are aligned: there's no corner to round.",
  "Empalme de radio {0} {1}.": "Fillet of radius {0} {1}.",
  "Corta la esquina entre dos líneas a una distancia": "Cuts the corner between two lines at a distance",
  "Distancia por la primera línea": "Distance along the first line", "Distancia por la segunda": "Distance along the second",
  "Chaflán {0} × {1} {2}.": "Chamfer {0} × {1} {2}.",
  "ARREGLO [R rectangular · P polar]": "ARRAY [R rectangular · P polar]", "Selecciona lo que se repite": "Select what to repeat",
  "¿Rectangular o Polar? R/P": "Rectangular or Polar? R/P", "Centro del arreglo": "Center of the array",
  "¿Cuántas copias en total?": "How many copies in total?", "Ángulo a cubrir": "Angle to fill",
  "{0} copia(s) alrededor del centro.": "{0} copy(ies) around the center.", "Filas": "Rows", "Columnas": "Columns",
  "Separación entre filas": "Row spacing", "Separación entre columnas": "Column spacing",
  "{0} copia(s) en {1} × {2}.": "{0} copy(ies) in {1} × {2}.",
  "Estira lo que agarres por cruce (de derecha a izquierda)": "Stretches what you grab by crossing (right to left)",
  "Primera esquina de la ventana de cruce": "First corner of the crossing window", "La ventana no tocó nada.": "The window didn't touch anything.",
  "Punto base del estirón": "Base point of the stretch", "Nada quedó dentro de la ventana.": "Nothing was inside the window.",
  "{0} entidad(es) estiradas ΔX {1}, ΔY {2}.": "{0} entity(ies) stretched ΔX {1}, ΔY {2}.",
  "Copia capa, color, grosor y tipo de línea de una entidad a otras": "Copies layer, color, lineweight and linetype from one entity to others",
  "Entidad de la que se copian las propiedades": "Entity to copy the properties from", "Entidades que van a igualarse": "Entities to match",
  "{0} entidad(es) igualadas a la capa «{1}».": "{0} entity(ies) matched to layer “{1}”.",
  "Une líneas, arcos y polilíneas que se tocan en una sola polilínea": "Joins touching lines, arcs and polylines into a single polyline",
  "Selecciona lo que se une (líneas, arcos, polilíneas)": "Select what to join (lines, arcs, polylines)",
  "Hacen falta al menos dos para unir.": "At least two are needed to join.", "No se unió nada.": "Nothing was joined.",
  "Agrupa lo seleccionado: picar uno es picar todos (Ctrl+G)": "Groups the selection: picking one picks all (Ctrl+G)",
  "Selecciona lo que se agrupa": "Select what to group", "Un grupo necesita al menos dos entidades.": "A group needs at least two entities.",
  "Grupo «{0}» con {1} entidades.": "Group “{0}” with {1} entities.",
  "Deshace el grupo de lo seleccionado (Ctrl+Shift+G)": "Ungroups the selection (Ctrl+Shift+G)", "Selecciona algo del grupo": "Select something in the group",
  "Deshace bloques, polilíneas, rayados, cotas y entidades ajenas en sus partes": "Breaks blocks, polylines, hatches, dimensions and foreign entities into their parts",
  "Selecciona lo que se explota": "Select what to explode",

  // --- bloques, fondos, suite --------------------------------------------------
  "Convierte lo seleccionado en un bloque": "Turns the selection into a block", "Selecciona lo que forma el bloque": "Select what makes up the block",
  "Punto base del bloque (por dónde se agarra al insertarlo)": "Base point of the block (where it's held when inserted)",
  "Nombre del bloque": "Block name", "Sin nombre: no se creó el bloque.": "No name: the block wasn't created.",
  "Bloque «{0}» con {1} entidad(es).": "Block “{0}” with {1} entity(ies).",
  "Inserta un bloque del dibujo o de la biblioteca del taller": "Inserts a block from the drawing or from the shop library",
  "No hay bloques todavía. Crea uno con BLOQUE.": "No blocks yet. Create one with BLOCK.",
  "· {0} ({1} entidades)": "· {0} ({1} entities)", "· {0} — biblioteca del taller": "· {0} — shop library",
  "¿Cuál bloque?": "Which block?", "No hay ningún bloque «{0}».": "There is no block “{0}”.",
  "Escala": "Scale", "Rotación": "Rotation", "¿Dónde va? (Escape termina)": "Where does it go? (Escape finishes)",
  "Guarda un bloque del dibujo en la biblioteca del taller": "Saves a block from the drawing into the shop library",
  "Este dibujo no tiene bloques.": "This drawing has no blocks.", "¿Cuál se guarda?": "Which one to save?", "Descripción": "Description",
  "«{0}» guardado en la biblioteca del taller.": "“{0}” saved in the shop library.",
  "Guardado en {0}. Está en todos tus dibujos.": "Saved in {0}. It's available in all your drawings.",
  "Enseña los bloques del dibujo y los del taller": "Lists the blocks in the drawing and in the shop library",
  "En este dibujo: {0} bloque(s).": "In this drawing: {0} block(s).", "En la biblioteca del taller: {0}.": "In the shop library: {0}.",
  "Trae las líneas de un PDF de arquitecto para calcar encima": "Brings the lines of an architect's PDF to trace over",
  "página {0}: {1}×{2} mm · {3} trazos": "page {0}: {1}×{2} mm · {3} strokes", "¿Qué página?": "Which page?",
  "¿A qué escala está impreso? (1:__)": "At what scale is it printed? (1:__)",
  "{0} líneas en la capa {1}, bloqueada.": "{0} lines on layer {1}, locked.",
  "Fondo importado: {0} líneas. La capa {1} está": "Background imported: {0} lines. Layer {1} is",
  "Prueba con IMAGENREF para meterlo como imagen y calcar encima.": "Try IMAGEREF to bring it in as an image and trace over it.",
  "Pone una foto o un escaneo debajo del dibujo, para calcar": "Puts a photo or a scan under the drawing, to trace",
  "Esquina inferior izquierda": "Lower-left corner", "Esquina superior derecha": "Upper-right corner",
  "Ese rectángulo no tiene tamaño.": "That rectangle has no size.",
  "Imagen puesta. No viaja al DXF: es referencia, no dibujo.": "Image placed. It doesn't travel to the DXF: it's a reference, not drawing.",
  "Trae una cocina de Taller 101 y le dibuja plantas y alzados": "Imports a Taller 101 kitchen and draws its plans and elevations",
  "«{0}» · {1}": "“{0}” · {1}", "{0} mueble(s): {1} bajo(s),": "{0} cabinet(s): {1} base,",
  "¿Acotar automáticamente? S/N": "Dimension automatically? Y/N", "{0} mueble(s) dibujados, {1} cota(s).": "{0} cabinet(s) drawn, {1} dimension(s).",
  "Cocina importada: {0} muebles, cada uno como bloque.": "Kitchen imported: {0} cabinets, each as a block.",
  "Vuelve a leer el .t101x y rehace los muebles, sin tocar tus anotaciones": "Re-reads the .t101x and rebuilds the cabinets without touching your annotations",
  "{0} mueble(s) rehechos; {1} entidad(es)": "{0} cabinet(s) rebuilt; {1} entity(ies)",
  "Muebles actualizados. Lo que dibujaste o anotaste a mano sigue ahí.": "Cabinets updated. What you drew or annotated by hand is still there.",
  "Una hoja de impresión por cada mueble importado": "One print sheet per imported cabinet",
  "{0} hoja(s): {1}": "{0} sheet(s): {1}", "{0} hojas creadas, una por mueble.": "{0} sheets created, one per cabinet.",
  "Deja el PDF, el DXF y el manifiesto en una carpeta para SUPERVISOR": "Leaves the PDF, the DXF and the manifest in a folder for SUPERVISOR",
  "¿En qué carpeta se deja el paquete?": "Which folder does the package go in?", "Paquete en {0}": "Package in {0}",
  "· {0} archivo(s) + manifiesto.json": "· {0} file(s) + manifiesto.json", "Listo para SUPERVISOR: {0} mueble(s),": "Ready for SUPERVISOR: {0} cabinet(s),",
  "Cuenta cuántas veces está insertado cada bloque": "Counts how many times each block is inserted",
  "No hay bloques insertados en el dibujo.": "There are no blocks inserted in the drawing.", "Cantidades:": "Quantities:", "{0} en total": "{0} in total",
  "Trae otro DXF como fondo bloqueado, y lo puede recargar": "Brings another DXF as a locked background, and can reload it",
  "{0} entidad(es) desde {1}, capa bloqueada.": "{0} entity(ies) from {1}, layer locked.",
  "Compara este dibujo con otro archivo y dice qué cambió": "Compares this drawing with another file and says what changed",
  "Contra {0}:": "Against {0}:", "{0} entidad(es) sólo en este dibujo": "{0} entity(ies) only in this drawing",
  "{0} entidad(es) sólo en el otro": "{0} entity(ies) only in the other one", "{0} iguales en los dos": "{0} the same in both",
  "Diferencias: +{0} / −{1}.": "Differences: +{0} / −{1}.",

  // --- hojas e impresión --------------------------------------------------------
  "{0} · Enter guarda · Esc cancela · vacío = automático": "{0} · Enter saves · Esc cancels · empty = automatic",
  "(automático)": "(automatic)", "Hoja nueva": "New sheet", "Hoja «{0}»": "Sheet “{0}”",
  "Se crea con una ventana ya encuadrada sobre el dibujo.": "It's created with a viewport already framed on the drawing.",
  "Lo que se deje en blanco lo rellena el plano solo: cliente, fecha y escala.": "Whatever is left blank the sheet fills in by itself: client, date and scale.",
  "Nombre de la hoja": "Sheet name", "Formato": "Size", "Ancho del papel": "Paper width", "Alto del papel": "Paper height",
  "Escala de la ventana": "Viewport scale", "El rótulo escribe esta escala solo.": "The title block writes this scale by itself.",
  "Pie de plano": "Title block", "Proyecto": "Project", "Cliente": "Client", "Dibujo": "Drawing", "Dibujó": "Drawn by",
  "Folio": "Sheet no.", "Revisión": "Revision", "Fecha": "Date", "— el del dibujo —": "— the drawing's —",
  "Crear la hoja": "Create the sheet", "La hoja necesita un nombre.": "The sheet needs a name.",
  "A la medida: entre 50 y 5000 mm por lado.": "Custom size: between 50 and 5000 mm per side.",
  "A la medida…": "Custom size…", "Carta · 279 × 216": "Letter · 279 × 216", "Tabloide · 432 × 279": "Tabloid · 432 × 279",
  "Hoja «{0}» en {1}, encuadrada sobre el dibujo.": "Sheet “{0}” in {1}, framed on the drawing.", "Hoja actualizada.": "Sheet updated.",
  "Hoja nueva, o edita la hoja abierta, en un cuadro": "New sheet, or edits the open sheet, in a dialog",
  "Hoja en {0}, encuadrada sobre el dibujo.": "Sheet in {0}, framed on the drawing.",
  "Cuadro de la hoja abierta: formato, escala y pie de plano": "Dialog for the open sheet: size, scale and title block",
  "Primero abre una hoja.": "Open a sheet first.", "Vuelve al espacio modelo": "Goes back to model space",
  "Cambia la escala de la ventana de la hoja": "Changes the scale of the sheet's viewport", "Escala 1:? ({0})": "Scale 1:? ({0})",
  "Ventana a 1:{0}. Las cotas se ajustaron para leerse en papel.": "Viewport at 1:{0}. Dimensions were adjusted to read on paper.",
  "Vuelve a centrar la ventana sobre todo el dibujo": "Re-centers the viewport on the whole drawing", "Ventana encuadrada.": "Viewport framed.",
  "Rellena el pie de plano de la hoja": "Fills in the sheet's title block", "Borra la hoja abierta": "Deletes the open sheet", "Hoja borrada.": "Sheet deleted.",
  "IMPRIMIR [TODO] — la hoja abierta, o todas en un PDF": "PRINT [ALL] — the open sheet, or all of them in a PDF",
  "No hay ninguna hoja. Crea una con PLANO.": "There is no sheet. Create one with SHEET.",
  "PDF listo: {0} hoja(s) en {1}": "PDF ready: {0} sheet(s) at {1}", "PDF con {0} hoja(s).": "PDF with {0} sheet(s).",
  "Guarda la hoja como PNG": "Saves the sheet as PNG", "Puntos por pulgada": "Dots per inch", "Imagen de {0}×{1} px guardada.": "Image of {0}×{1} px saved.",
  "Imprimir": "Print", "{0} hoja(s) · sale el PDF de la hoja con su marco y su pie,": "{0} sheet(s) · the sheet's PDF goes out with its frame and title block,",
  "Impresora": "Printer", "Las instaladas en esta PC, las mismas que ve Windows.": "The ones installed on this PC, the same Windows sees.",
  "Copias": "Copies", "A color": "In color", "Abrir el cuadro de Windows": "Open the Windows dialog",
  "Para tocar bandeja, dúplex o tamaño de papel.": "To change tray, duplex or paper size.",
  "Manda la hoja a una impresora de la PC (Ctrl+P)": "Sends the sheet to a printer on this PC (Ctrl+P)",
  "No hay ninguna hoja que imprimir. Crea una con PLANO.": "There is no sheet to print. Create one with SHEET.",
  "Imprimir en papel sólo funciona en la aplicación instalada.": "Printing on paper only works in the installed application.",
  "Impresión cancelada.": "Printing cancelled.", "Preparando la hoja…": "Preparing the sheet…", "No se pudo imprimir:": "Couldn't print:",
  "Mandado a imprimir: {0} hoja(s){1}.": "Sent to print: {0} sheet(s){1}.", "{0} hoja(s) a la impresora{1}.": "{0} sheet(s) to the printer{1}.",
  "Vista previa": "Preview", "Vista previa de impresión": "Print preview",
  "Así sale en «{0}» en {1}: la hoja centrada en el papel. El gris es lo que la impresora no alcanza.": "This is how it prints on “{0}” in {1}: the sheet centered on the paper. Grey is what the printer can't reach.",
  "Papel": "Paper", "Tamaño de papel": "Paper size", "Como la hoja": "Same as the sheet",
  "Centrado en el papel (no en los márgenes)": "Centered on the paper (not on the margins)",
  "Ajustar al área imprimible": "Fit to the printable area",
  "Enseña cómo sale la hoja en la impresora y el papel elegidos": "Shows how the sheet comes out on the chosen printer and paper",
  "La hoja ({0}) es más grande que el papel ({1}): se escala a {2} %.": "The sheet ({0}) is larger than the paper ({1}): it's scaled to {2} %.",
  "Sale al {0} %.": "Prints at {0} %.", "Sale a tamaño real.": "Prints at true size.",
  "Se recorta: {0} mm se salen del área imprimible.": "It gets cropped: {0} mm fall outside the printable area.",
  "Plano {0}": "Sheet {0}",

  // --- motor (mensajes que llegan del servidor) --------------------------------
  "Buscando en la caché…": "Looking in the cache…", "Buscando las referencias externas…": "Looking for external references…",
  "Convirtiendo el DWG ({0} MB)… en un archivo grande esto es lo que más tarda": "Converting the DWG ({0} MB)… on a large file this is what takes longest",
  "El PDF tiene {0} página(s)": "The PDF has {0} page(s)", "El bloque necesita un nombre": "The block needs a name",
  "El dibujo no tiene ninguna hoja de impresión.": "The drawing has no print sheet.",
  "Este dibujo no trae muebles importados de Taller 101": "This drawing has no cabinets imported from Taller 101",
  "Guardando en la caché para la próxima vez…": "Saving to the cache for next time…", "Importando el modelo…": "Importing the model…",
  "Importando las hojas…": "Importing the sheets…", "Leyendo el DXF ({0} MB)…": "Reading the DXF ({0} MB)…",
  "La capa 0 no se borra": "Layer 0 can't be deleted", "La capa 0 no se renombra": "Layer 0 can't be renamed",
  "No hay nada seleccionado": "Nothing is selected", "No se pueden tener más de {0} dibujos abiertos": "No more than {0} drawings can be open",
  "Ya existe la capa «{0}»": "Layer “{0}” already exists", "Ya existe un bloque llamado «{0}»": "A block named “{0}” already exists",
  "Valor inválido para «{0}»": "Invalid value for “{0}”",
  "Esta hoja sale en blanco: no llegó ningún trazo a la ventana.": "This sheet comes out blank: no stroke reached the viewport.",
  "Revisa el encuadre de la ventana.": "Check the viewport framing.",
  "descargando": "downloading", "instalando": "installing", "listo": "ready", "manual": "manual",
  "Trabajando": "Working", "Abriendo…": "Opening…", "Guardando…": "Saving…",

  // --- pie de ventana, tipos de línea, valores ---------------------------------
  "DWG · motor propio": "DWG · built-in engine", "DWG · ODA File Converter": "DWG · ODA File Converter", "DWG no disponible": "DWG not available",
  "Se usa el ODA File Converter, que es el más fiel.": "The ODA File Converter is used, which is the most faithful.",
  "LibreDWG y acad-ts, dentro del programa. Instalar el ODA File Converter (gratuito) convierte más rápido y más fiel.": "LibreDWG and acad-ts, built into the program. Installing the ODA File Converter (free) converts faster and more faithfully.",
  "No se encontró con qué leer DWG en esta máquina.": "Nothing to read DWG with was found on this machine.",
  "Clic: instalar o actualizar el ODA.": "Click: install or update the ODA.",
  "{0}\nClic: instalar o actualizar el ODA.": "{0}\nClick: install or update the ODA.",
  "Z E · MD · REF · AYUDA": "Z E · MD · OSNAP · HELP",
  "Continua": "Continuous", "Ejes ____ _ ____ _ ____": "Center ____ _ ____ _ ____", "Oculta __ __ __ __ __": "Hidden __ __ __ __ __",
  "Trazos __ __ __ __": "Dashed __ __ __ __", "Ficticia ___ _ _ ___": "Phantom ___ _ _ ___", "Puntos . . . . . . .": "Dotted . . . . . . .",
  "continuous": "continuous",
  "Instalado: ODA File Converter {0}.": "Installed: ODA File Converter {0}.", "(versión desconocida)": "(unknown version)",
  "No está instalado. Ahora los DWG se convierten con el motor propio (LibreDWG), que es más lento y menos fiel.": "It's not installed. DWG files are currently converted with the built-in engine (LibreDWG), which is slower and less faithful.",
  "Última versión según Taller 101: {0}.": "Latest version according to Taller 101: {0}.",
  "Última versión según la página de ODA: {0}.": "Latest version according to the ODA page: {0}.",
  "No se pudo consultar la última versión (¿sin internet?).": "Couldn't check the latest version (no internet?).",
  "Es gratuito; lo baja de opendesign.com (~60 MB) y corre su instalador: hay que aceptar su licencia y el permiso de Windows.": "It's free; it downloads it from opendesign.com (~60 MB) and runs its installer: you must accept its license and the Windows prompt.",
  "Ahora no": "Not now",
  "Dibujos": "Drawings", "Todos los archivos": "All files", "Imágenes": "Images", "Dibujo Taller 101": "Taller 101 drawing",

  // --- 0.20.0 ----------------------------------------------------------------
  "Cotas del documento": "Document dimensions", "Flechas": "Arrows",
  "Estilo completo…": "Full style…", "Todo el estilo de cota (ESTILOCOTA)": "The whole dimension style (DIMSTYLE)",
  "Altura del texto de las cotas, en unidades del dibujo": "Dimension text height, in drawing units",
  "Tamaño de las flechas o palomitas, en unidades del dibujo": "Arrow or tick size, in drawing units",
  "El tamaño tiene que ser mayor que cero.": "The size has to be greater than zero.",
  "Texto de las cotas": "Dimension text", "Flechas de las cotas": "Dimension arrows",
  "Capa {0}": "Layer {0}", "Cerrar (Esc)": "Close (Esc)",
  "Justificado": "Justified", "Izquierda del origen": "Left of the origin", "Centrado en el origen": "Centered on the origin",
  "Derecha del origen": "Right of the origin",
  "Tamaño ({0})": "Size ({0})", "encadenar al base": "chain to the base size",
  "Encadenada al tamaño base del documento: si el base cambia, esta cota cambia en proporción.": "Chained to the document base size: if the base changes, this dimension changes in proportion.",
  "Los cambios se ven al momento · clic fuera o Esc cierra": "Changes show instantly · click outside or Esc closes",
  "entidades": "entities",
  "Enter acepta · Esc cancela": "Enter accepts · Esc cancels", "Espacio o Enter aceptan · Esc cancela": "Space or Enter accept · Esc cancels",
  "Punto de referencia (o teclea el factor)": "Reference point (or type the factor)",
  "Punto nuevo: hasta dónde debe llegar (o teclea el factor)": "New point: where it should reach (or type the factor)",
  "El punto de referencia es el mismo que la base.": "The reference point is the base point.",
  "El factor tiene que ser mayor que cero.": "The factor has to be greater than zero.",
    "Escala lo seleccionado: punto base, punto de referencia y punto nuevo (o teclea el factor)": "Scales the selection: base point, reference point and new point (or type the factor)",
  "Esquina opuesta (o teclea ancho, Enter, alto, Enter)": "Opposite corner (or type width, Enter, height, Enter)",
  "Alto ({0} {1} × ?)": "Height ({0} {1} × ?)",
  "Texto (uno o varios renglones): Enter guarda, Alt+Enter hace renglón nuevo": "Text (one or more lines): Enter saves, Alt+Enter makes a new line",
  "Enter guarda · Alt+Enter hace renglón nuevo.": "Enter saves · Alt+Enter makes a new line.",
  "Editar texto": "Edit text",
  "Patrón del rayado": "Hatch pattern", "Pasa el ratón para ver la previa · Enter o clic confirma · Esc cancela": "Hover to preview · Enter or click confirms · Esc cancels",
  "Elige el patrón en la galería (Enter confirma)": "Pick the pattern in the gallery (Enter confirms)",
  "Raya una polilínea cerrada o un círculo: se elige el patrón en una galería con previa": "Hatches a closed polyline or a circle: the pattern is picked in a gallery with a live preview",
  "Diagonal 45°": "Diagonal 45°", "Diagonal doble (acero)": "Double diagonal (steel)", "Diagonal punteada (bronce)": "Dashed diagonal (bronze)",
  "Diagonal ancha (plástico)": "Wide diagonal (plastic)", "Cruzada 45° (aislante)": "Cross 45° (insulation)", "Horizontal": "Horizontal", "Vertical": "Vertical",
  "Cuadrícula": "Grid", "Cuadrícula triple": "Triple grid", "Puntos": "Dots", "Ladrillo": "Brick", "Concreto": "Concrete", "Arena": "Sand", "Tierra": "Earth",
  "Acero": "Steel", "Madera (veta)": "Wood (grain)", "Aislante": "Insulation", "Vidrio": "Glass", "Hexágonos": "Hexagons",
  "Tamaño de cotas": "Dimension size",
  "Altura del texto de las cotas en esta hoja. Cada hoja tiene el suyo; el modelo no cambia.": "Dimension text height on this sheet. Each sheet has its own; the model doesn't change.",
  "El tamaño de cotas tiene que ser mayor que cero.": "The dimension size has to be greater than zero.",
  "Hoja «{0}» en {1}, con la ventana sobre el recuadro elegido.": "Sheet “{0}” in {1}, with the viewport on the chosen box.",
  "Recuadra una zona del modelo y crea una hoja cuya ventana enseña justo eso": "Box a zone of the model and create a sheet whose viewport shows exactly that",
  "Se usa desde el modelo: encuadra ahí lo que va a la hoja.": "Use it from the model: box there what goes on the sheet.",
  "Primera esquina de lo que va en la hoja": "First corner of what goes on the sheet",
  "El recuadro no tiene tamaño.": "The box has no size.",
  "Hoja nueva (todo el dibujo)": "New sheet (the whole drawing)", "Ventana a hoja (recuadrar)": "Viewport to sheet (box it)",
  "Proyección perpendicular": "Perpendicular projection",
  "Cuadrado": "Rectangle", "Editar": "Edit",
  "Un parpadeo casi imperceptible del lienzo cuando un comando cambia algo": "A barely visible flicker of the canvas when a command changes something",
  "Arrastra las esquinas, los lados o el marco de la ventana; el interior mueve el dibujo. Esc termina": "Drag the viewport's corners, sides or frame; the inside pans the drawing. Esc ends",
  "Ventana": "Viewport", "en": "at",
  "Enciende o apaga los handles de las ventanas de la hoja: esquinas y lados cambian el tamaño, el marco la mueve, el interior corre el dibujo": "Toggles the sheet viewports' handles: corners and sides resize, the frame moves it, the inside pans the drawing",
  "Edición de ventanas terminada.": "Viewport editing ended.",
  "Agrega una ventana a la hoja: se recuadra con dos esquinas sobre el papel": "Adds a viewport to the sheet: box it with two corners on the paper",
  "Primera esquina de la ventana, sobre la hoja": "First corner of the viewport, on the sheet",
  "La ventana tiene que medir al menos 10 × 10 mm.": "The viewport has to be at least 10 × 10 mm.",
  "Ventana {0} agregada ({1} × {2} mm). EDITARVENTANA para acomodarla.": "Viewport {0} added ({1} × {2} mm). EDITVIEWPORT to arrange it.",
  "Quita una ventana de la hoja (clic sobre ella)": "Removes a viewport from the sheet (click on it)",
  "La hoja necesita al menos una ventana; no se borra la única.": "The sheet needs at least one viewport; the only one can't be removed.",
  "Ahí no hay ventana.": "There's no viewport there.", "Ventana {0} quitada.": "Viewport {0} removed.",
  "Ventana {0}: {1} × {2} mm en ({3}, {4}).": "Viewport {0}: {1} × {2} mm at ({3}, {4}).",
  "Otra…": "Other…", "Escala 1:?": "Scale 1:?",
  "La escala tiene que ser mayor que cero.": "The scale has to be greater than zero.",
  "Editar las ventanas de la hoja con el ratón: esquinas y lados cambian el tamaño, el marco mueve, el interior corre el dibujo (VP)": "Edit the sheet viewports with the mouse: corners and sides resize, the frame moves, the inside pans the drawing (VP)",
  "Ventana nueva en la hoja (NV)": "New viewport on the sheet (NV)",
  "Hay una versión nueva de shape101: {0} (tienes la {1}).": "There is a new shape101 version: {0} (you have {1}).",
  "Ver la descarga": "See the download",
};
